all:
	gcc -o development_net.o -c -I /usr/local/src/perpetuum/include/ development_net.c
	gcc -DPETRINET_SINGLETONS -o development_net.o -c -I /usr/local/src/perpetuum/include/ development_net.c
	gcc -DPETRINET_SINGLETONS -DPETRINET_CODED_FOR_ONE -o development_net.o -c -I /usr/local/src/perpetuum/include/ development_net.c
