all:
	gcc -o development_net.o -c -I /usr/local/src/perpetuum/include/ development_net.c
	gcc -DPETRINET_SINGLETONS -o development_net.o -c -I /usr/local/src/perpetuum/include/ development_net.c
	gcc -DPETRINET_SINGLETONS -DPETRINET_GLOBAL_NAME=my1st -o development_net.o -c -I /usr/local/src/perpetuum/include/ development_net.c
